version: "3"
services:
  app:
    build:
      args:
        user: ${APP_USER}
        uid: 1000
      context: ./
      dockerfile: ./.docker/Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - redis

    networks:
      - app
  nginx:
    image: nginx:1.17-alpine
    container_name: app-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - app
  queue:
    build:
      args:
        user: ${APP_USER}
        uid: 1000
      context: ./
      dockerfile: ./.docker/Dockerfile
    restart: unless-stopped
    container_name: app-queue
    command: "php artisan queue:work"
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - app
  redis:
    container_name: app-redis
    image: redis:latest
    networks:
      - app
networks:
  app:
    driver: bridge
