name: CI Homologação
on:
  pull_request:
    branches:
      - develop
jobs:
  tests:
    name: CI
    runs-on: ubuntu-18.04
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.0'

#-------------------------------------------------------------------------------------------------------------

      # checkout branch
      - uses: actions/checkout@v2

#-------------------------------------------------------------------------------------------------------------
      - name: notify
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          args: '@everyone preparando o Build e executando a cobertura de código :clock:'

#-------------------------------------------------------------------------------------------------------------

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit

#-------------------------------------------------------------------------------------------------------------
      - name: Finished Build and Tests
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          args: '@everyone os testes froam finalizados :white_check_mark:'

#-------------------------------------------------------------------------------------------------------------
  deploy:
    name: CD
    needs: tests
    runs-on: ubuntu-latest
    environment: homolog
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: Prepare Deploy
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          args: '@everyone preparando o deploy em Homologação :clock:'

      - name: Deploy to server of Homologation
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --exclude .git --exclude .docker --exclude .github"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: /home/${{ secrets.SSH_USER }}/ci-cd

      - name: Execute commands SSH
        uses: appleboy/ssh-action@master
        env:
          USER_PASS: "${{ secrets.USER_PASS }}"
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: '${{ secrets.SSH_PRIVATE_KEY }}'
          port: ${{ secrets.SSH_PORT }}
          envs: USER_PASS
          script: |
            cd ci-cd/
            echo $USER_PASS | sudo -S docker-compose up -d
            echo $USER_PASS | sudo -S docker-compose exec -T app composer install
            echo $USER_PASS | sudo -S docker-compose exec -T app php artisan migrate --force

      - name: Finish Deploy
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          args: '@everyone Finalizado o deploy em Homologação :white_check_mark: :heart: :partying_face:'


